### ISSUE TITLE
Rename repo to hyperapp/server ?

### ISSUE THREAD

**Issue by lukejacksonn** [hyperapp/server#3]
![giphy](https://user-images.githubusercontent.com/1457604/27717166-6774bcb8-5d3b-11e7-95e2-2470d9879b64.gif)

**Comment by benjaminj6** [comment]
I believe the plan is to remove the repo in a bit and integrate SSR into hyperapp/hyperapp.

**Comment by lukejacksonn** [comment]
😮

**Comment by benjaminj6** [comment]
I believe the conversation in [hyperapp/hyperapp](https://github.com/hyperapp/hyperapp/issues/257) is the place to be for SSR chats right now. And that will determine whether we keep this repo up or not.

**Comment by jbucaran** [comment]
@benjaminj6 I know, that's what we had been discussing, but after [this](https://github.com/hyperapp/router), I've reconsidered. 🙇 

Now, while it makes sense for the Router, I don't know if it makes sense for SSR/toString. It does to me at first glance, but what do you guys think?

**Comment by benjaminj6** [comment]
Ahhhh that makes sense. I haven't been keeping up to date too well — getting married in a week, and starting a new job soon too so those have taken most of my time. 🎉

My initial reaction is that it makes sense to include as a separate repo for SSR/toString. If we're not shooting for the all-in-one approach any more, makes sense that SSR would be one of those things to separate

**Comment by jbucaran** [comment]
@benjaminj6 I've renamed the repo to `server`. When we have something more concrete, let's publish `@hyperapp/server`.
