### ISSUE TITLE
Generating `data-hyperappid` 

### ISSUE THREAD

**Issue by nitin42** [hyperapp/server#7]
HyperApp should also generate `data-hyperappid` attribute to uniquely identify the components within the DOM. Since we are using `renderToString()` to generate the html, this can be easily integrared. 

```javascript
<div data-hyperappid='some_id'>
  <input data-hyperappid='some_other_id' />
</div>
```
```
{
  id: 'some_id',
  node: 'div',
  children: [
     {
       id: '.1oqi7occu80.0.0',
       node: InputRef,
       children: []
     }
  ] 
}
```

**Comment by SkaterDad** [comment]
Can you explain why this would be needed?

It would add a lot of bytes to the HTML being sent to the client.

**Comment by nitin42** [comment]
Sure! 

Internally when apps (built with HyperApp) are rendered on the client, we build a representation of references to the nodes to develop the markup.

Like this

```
{
  id: 'some_id',
  node: 'div',
  children: [
     {
       id: 'some_other_id',
       node: InputRef,
       children: []
     }
  ] 
}
```

Here each node has (will have if we implement) an id and each children also keeps an id. Now that apps can be rendered on the server, sending a serialised version of the entire tree could be an expensive operation. To avoid this we can introduce `data-ids` so that when apps are rendered on the server, the only data an app will have is an id.

```
<div some_id>
    <input some_other_id/>
</div>
```
Now we can convert this markup back into the data structure I mentioned in the above example. This process is called inflating of trees which means serialising and reproducing the state of the entire DOM tree.

Makes sense ?

**Comment by nitin42** [comment]
We could save a lot of bytes by rendering to a stream though!

**Comment by SkaterDad** [comment]
I think I see what you're trying to do now.  Instead of looping through all of the HTML elements to hydrate them (hyperapp/hyperapp#267), you could just calculate the whole virtual node tree directly?

**Comment by nitin42** [comment]
Yes, by serialising !

**Comment by jbucaran** [comment]
@nitin42 Does this somehow invalidate #267? 

/cc @andyrj

**Comment by andyrj** [comment]
So is this about avoiding the extra initial patch/diff of the vdom on client first render for ssr apps primarily?  Are there other use cases?  I know #267 isn't perfect but not sure I like adding data-ids to dom either.  Why not just expose node.data.key to the dom (I get that it would have to be serializable and I don't think it is atm)?

**Comment by andyrj** [comment]
My other question is won't that require a larger addition of code to hyperapp core than #267, which primarily reuses the current render/patch to accomplish the same thing without the need for extra data in the dom?

**Comment by nitin42** [comment]
Yes ! It may add. But it helps in cache direct reference to the node. So we will only look up through `some_id` once. These ids will help in storing references to the DOM nodes. Internally in HyperApp, all the DOM nodes are appended at once to the root element. Using these ids will allow us to quickly find those element (DOM nodes) later which will be useful in SSR.

**Comment by andyrj** [comment]
What other use were you thinking this has for ssr?  I can see some possibilities for optimizing patch, but struggling to think of more use for ssr.  Just wondering what I am overlooking.

**Comment by nitin42** [comment]
The main use is to find the nodes on the server with unique ids as its the only way to find them on the server !

**Comment by nitin42** [comment]
This makes sure which nodes will be referenced!

**Comment by andyrj** [comment]
This must be something streaming specific because I'm still not seeing when that would be needed at the moment.  If app() is rendering to undom, why do we need external references to the vdom nodes during that process?  Also since hyperapp is pure and view = (state) => {}, so long as the same state is client side as was rendered server side I don't see the need for extra id's in that case.  And I see serializing the rendered state into the html as part of ssr in general.

If this is about avoiding the hydrate(), we could pre-build just the tag structure and serialize that to the output html for JSON.parse() client side to use as the initial node...  but I don't think that needs additional id's to accomplish.

**Comment by nitin42** [comment]
> Also since hyperapp is pure and view = (state) => {}, so long as the same state is client side as was rendered server side I don't see the need for extra id's in that case

Then we might not need to introduce this (ids).

> I see serializing the rendered state into the html as part of ssr in general.

Currently do we inflate the component trees ? IDK yet 😅

**Comment by andyrj** [comment]
I'm still not 100% certain I understand what you mean by inflate the component tree, but if I understand the gist of what this is about really then we could do this to avoid the hydrate().

```html
<html>
<head>
  <script id='state' type='application/json'>
    { count: 0 }
  </script>
  <script id='nodes' type='application/json'>
    { tag: 'div', data: {}, children: [
      ..... // imagine I typed out the rest of the relevant vdom here
    ]}
  </script>
</head>
</html>
```
then we could change app() to:
```js
node = JSON.parse(document.getElementById('nodes').innerHTML)
```

or add an optional argument to app to allow passing this in by the user...

**Comment by nitin42** [comment]
🤔  I could give you an example but I'm turning in (different time zones 😅 )

**Comment by jbucaran** [comment]
Did anyone say no changes to core? 😋🍩

**Comment by nitin42** [comment]
Hehe! Yes. btwn @andyrj I am still not sure about this until we land [#238](https://github.com/hyperapp/hyperapp/issues/)

**Comment by jbucaran** [comment]
@nitin42 https://github.com/hyperapp/hyperapp/issues/238 ? 🤔😕
